### PR TITLE
Refactor count_repositories

### LINKED ISSUE #474: Counting
Hello, @vbrandl!

I am struggling to understand what `count_repositories` function do:

https://github.com/vbrandl/hoc/blob/ecbc63f522653e4be76002b115bf8b85db37007d/src/count.rs#L4-L27

There are two issues:

1) What repositories this function counts? What is repository, if it is a directory path?
2) What is exact algorithm? I can see that function counts 5-level nested directories, but why? Why not 4 or 6-level nested? This number comes from some limitation?

I may want to refactor this function, if you would clarify these issues. Thanks!

### PR DESCRIPTION
**Pull request by Masynchin**
Closes #474.

### CODE REVIEW

**Comment by Masynchin** [comment]
@vbrandl I am new to Rust, so it can be things to improve (but clippy didn't find anything). I am looking for your review.

I also have this questions:

1) Should we add tests for this function? I manually tested this code and it works fine, but this can't be trusted.
2) Should we add documentation for this function? We can add [your explanation](https://github.com/vbrandl/hoc/issues/474#issuecomment-1214402801) as a reason for this nested directories.

**Comment by vbrandl** [comment]
I would appreciate both:
1. For the tests, I would like to check if it works correctly for:
   * `foo/bar` should return `0`
   * `foo/bar/baz` should return `1`
   * `foo/bar/baz` and `qux/bar/baz` should return `2`
   * `foo/bar/baz/qux` and `foo/bar/baz/foo` should return `1`

   I already use the `tempdir` crate for other tests, so you can use that crate to create the test layouts.
2. For the documentation I think it's enough to just copy my comment from the GitHub issue

**Comment by vbrandl** [comment]
Do you want to try implementing the tests yourself? If not, I'll do it later.

**Comment by Masynchin** [comment]
Sorry for delay, I was struggling with creating nested directories with `tempfile` crate. The documentation is lacking of such example. I created appropriate issue and it was resolved exactly one minute ago. I will try to do it myself.

**Comment by Masynchin** [comment]
@vbrandl should the tests be in `tests/count.rs` or in `src/count.rs`?

**Comment by vbrandl** [comment]
Put it in `tests/count.rs`. If you have to move some structs or functions from `pub(crate)` to `pub`, that's fine.

**Comment by Masynchin** [comment]
@vbrandl done! Maybe it is too many unwraps, let me know if I can reduce them or refactor this. Otherwise, documentation and tests added, all tests passes.

**Comment by Masynchin** [comment]
> Otherwise, documentation and tests added, ~all tests passes~.

Wrong, only new tests. I didn't run non-new tests

**Pull request merged**
